# Version 1.2
substitutions:
  device_name: d12-frequency-converter
  friendly_name: "D12 Frequency Converter"
  modbus_address: "1"  # Change to match your device address (P6.00)

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0  # Disable UART logging to avoid conflicts with Modbus

# Enable Home Assistant API
api:
#  encryption:
#    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

captive_portal:

# Configure UART for RS485
uart:
  id: mod_bus
  tx_pin: GPIO1  # TX pin (D10 on D1 mini)
  rx_pin: GPIO3  # RX pin (D9 on D1 mini)
  baud_rate: 19200
  stop_bits: 1
  parity: NONE
  # For RS485 adapter, connect:
  # - TX to DI
  # - RX to RO
  # - DE/RE to GPIO5 (D1) for flow control (optional)

# Modbus Controller
modbus:
  id: modbus1
  uart_id: mod_bus
  flow_control_pin: GPIO5  # Optional: DE/RE control pin for RS485 adapter

modbus_controller:
  - id: d12_vfd
    address: ${modbus_address}
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 2s
    command_throttle: 50ms  # Add 50ms delay between commands to reduce collisions

# ===== SENSORS (Read-only monitoring) =====
sensor:
  # Output Frequency (Hz)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Output Frequency"
    id: output_frequency
    register_type: holding
    address: 0x2103
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Set Frequency (Hz)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Set Frequency"
    id: set_frequency
    register_type: holding
    address: 0x2102
    unit_of_measurement: "Hz"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Output Current (A)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Output Current"
    id: output_current
    register_type: holding
    address: 0x2104
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Bus Voltage (V)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Bus Voltage"
    id: bus_voltage
    register_type: holding
    address: 0x2105
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 0

  # Output Voltage (V)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Output Voltage"
    id: output_voltage
    register_type: holding
    address: 0x2106
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 0

  # Module Temperature (°C)
  # Note: Some D12 models may not support this register
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Temperature"
    id: module_temperature
    register_type: holding
    address: 0x210D
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    skip_updates: 10  # Poll less frequently if device doesn't always respond
    filters:
      - multiply: 0.1

  # PID Feedback Value (Raw percentage 0-100%)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "PID Feedback"
    id: pid_feedback
    register_type: holding
    address: 0x210E
    state_class: measurement
    accuracy_decimals: 2
    internal: true  # Hide raw value, use pressure sensor instead
    filters:
      - multiply: 0.01

  # PID Setpoint (Raw percentage 0-100%)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "PID Setpoint"
    id: pid_setpoint
    register_type: holding
    address: 0x210F
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # Pressure Sensor (4-20mA current input via ACI terminal)
  # IMPORTANT: Configure D12 VFD parameters first:
  #   P2.04 = 4.00 (ACI input lower limit, 4mA)
  #   P2.05 = 20.00 (ACI input upper limit, 20mA)
  #   P2.06 = 0.0% (ACI lower limit corresponding setting)
  #   P2.07 = 100.0% (ACI upper limit corresponding setting)
  #   P3.00 hundreds digit = 1 (PID feedback input channel = ACI)
  #   P3.18 = your sensor's max range in MPa (e.g., 1.00 for 0-1 MPa sensor)
  - platform: template
    name: "Pressure"
    id: pressure_sensor
    unit_of_measurement: "bar"
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 2
    icon: mdi:gauge
    lambda: |-
      // Convert PID feedback percentage to pressure
      // Adjust the multiplier (10.0) to match your sensor range
      // Example: For 0-10 bar sensor, use 10.0
      //          For 0-16 bar sensor, use 16.0
      //          For 0-1 MPa sensor (=10 bar), use 10.0
      if (id(pid_feedback).state >= 0) {
        return id(pid_feedback).state * 10.0;  // Change 10.0 to your sensor's max pressure
      } else {
        return 0.0;
      }
    update_interval: 2s

  # Pressure Setpoint (converted from PID setpoint)
  - platform: template
    name: "Pressure Setpoint"
    id: pressure_setpoint
    unit_of_measurement: "bar"
    device_class: pressure
    state_class: measurement
    accuracy_decimals: 2
    icon: mdi:gauge-empty
    lambda: |-
      // Convert PID setpoint percentage to pressure
      // Must match the same multiplier as pressure_sensor above
      if (id(pid_setpoint).state >= 0) {
        return id(pid_setpoint).state * 10.0;  // Change 10.0 to your sensor's max pressure
      } else {
        return 0.0;
      }
    update_interval: 2s

  # Status Word (raw for debugging)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Status Word"
    id: status_word
    register_type: holding
    address: 0x2101
    internal: true
    skip_updates: 10

  # Power Calculation (approximation: V * I * sqrt(3) for 3-phase)
  - platform: template
    name: "Estimated Power"
    id: estimated_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 0
    lambda: |-
      if (isnan(id(output_voltage).state) || isnan(id(output_current).state)) {
        return 0.0;
      }
      return id(output_voltage).state * id(output_current).state * 1.732;
    update_interval: 2s

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# ===== BINARY SENSORS (Status indicators) =====
binary_sensor:
  # Running Status (BIT0 of status word)
  - platform: template
    name: "Running"
    id: is_running
    device_class: running
    lambda: |-
      return ((int)id(status_word).state & 0x0001) != 0;

  # Stop Status (BIT1)
  - platform: template
    name: "Stopped"
    id: is_stopped
    lambda: |-
      return ((int)id(status_word).state & 0x0002) != 0;

  # Jog Status (BIT2)
  - platform: template
    name: "Jogging"
    id: is_jogging
    lambda: |-
      return ((int)id(status_word).state & 0x0004) != 0;

  # Forward Direction (BIT3)
  - platform: template
    name: "Forward Direction"
    id: is_forward
    lambda: |-
      return ((int)id(status_word).state & 0x0008) != 0;

  # Reverse Direction (BIT4)
  - platform: template
    name: "Reverse Direction"
    id: is_reverse
    lambda: |-
      return ((int)id(status_word).state & 0x0010) != 0;

  # Overload Pre-alarm (BIT10)
  - platform: template
    name: "Overload Warning"
    id: overload_warning
    device_class: problem
    lambda: |-
      return ((int)id(status_word).state & 0x0400) != 0;

  # Status
  - platform: status
    name: "Status"

# ===== NUMBERS (Control inputs) =====
number:
  # Frequency Setpoint Control (-100.00% to 100.00% of max frequency)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Frequency Setpoint"
    id: frequency_setpoint
    register_type: holding
    address: 0x2001
    min_value: -100
    max_value: 100
    step: 0.1
    unit_of_measurement: "%"
    mode: slider
    multiply: 100
    use_write_multiple: false

# ===== SWITCHES (Control commands) =====
switch:
  # Forward Run
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Run Forward"
    id: run_forward
    register_type: holding
    address: 0x2000
    icon: mdi:play
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0012 = Forward, 0x0001 = Stop
    write_lambda: |-
      if (x) {
        return 0x0012;
      } else {
        return 0x0001;
      }

  # Reverse Run
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Run Reverse"
    id: run_reverse
    register_type: holding
    address: 0x2000
    icon: mdi:play-reverse
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0022 = Reverse, 0x0001 = Stop
    write_lambda: |-
      if (x) {
        return 0x0022;
      } else {
        return 0x0001;
      }

  # Stop Command (helper switch)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Stop Switch"
    id: vfd_stop_switch
    internal: true
    register_type: holding
    address: 0x2000
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0001 = Stop
    write_lambda: |-
      return 0x0001;

  # Forward Jog (helper switch)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Jog Forward Switch"
    id: vfd_jog_forward_switch
    internal: true
    register_type: holding
    address: 0x2000
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0013 = Forward Jog
    write_lambda: |-
      return 0x0013;

  # Reverse Jog (helper switch)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Jog Reverse Switch"
    id: vfd_jog_reverse_switch
    internal: true
    register_type: holding
    address: 0x2000
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0023 = Reverse Jog
    write_lambda: |-
      return 0x0023;

  # Fault Reset (helper switch)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Fault Reset Switch"
    id: vfd_fault_reset_switch
    internal: true
    register_type: holding
    address: 0x2002
    use_write_multiple: false
    skip_updates: 999  # Write-only, don't poll for status
    # 0x0002 = Fault Reset
    write_lambda: |-
      return 0x0002;

# ===== BUTTONS (Single-action commands) =====
button:
  # Stop Command
  - platform: template
    name: "Stop"
    icon: mdi:stop
    on_press:
      then:
        - switch.turn_on: vfd_stop_switch
        - delay: 50ms
        - switch.turn_off: vfd_stop_switch

  # Forward Jog
  - platform: template
    name: "Jog Forward"
    icon: mdi:debug-step-over
    on_press:
      then:
        - switch.turn_on: vfd_jog_forward_switch
        - delay: 50ms
        - switch.turn_off: vfd_jog_forward_switch

  # Reverse Jog
  - platform: template
    name: "Jog Reverse"
    icon: mdi:debug-step-into
    on_press:
      then:
        - switch.turn_on: vfd_jog_reverse_switch
        - delay: 50ms
        - switch.turn_off: vfd_jog_reverse_switch

  # Fault Reset
  - platform: template
    name: "Fault Reset"
    icon: mdi:restore-alert
    on_press:
      then:
        - switch.turn_on: vfd_fault_reset_switch
        - delay: 50ms
        - switch.turn_off: vfd_fault_reset_switch

  # Restart ESP
  - platform: restart
    name: "Restart"

# ===== TEXT SENSORS (Status information) =====
text_sensor:
  # Operation Status
  - platform: template
    name: "Operation Status"
    id: operation_status
    icon: mdi:information
    update_interval: 2s
    lambda: |-
      if (id(is_running).state) {
        if (id(is_forward).state) return {"Running Forward"};
        if (id(is_reverse).state) return {"Running Reverse"};
        return {"Running"};
      } else if (id(is_jogging).state) {
        return {"Jogging"};
      } else if (id(is_stopped).state) {
        return {"Stopped"};
      }
      return {"Unknown"};

  # WiFi Info
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"

# ===== SELECT (Parameter configuration) =====
select:
  # Run Command Channel (P0.02)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Run Command Source"
    address: 0x0002  # P0.02
    value_type: U_WORD
    skip_updates: 60  # Only poll every 2 minutes (config parameter, rarely changes)
    optionsmap:
      "Panel": 0
      "Terminal": 1
      "Communication": 2

  # Frequency Source Selection (P0.03)
  - platform: modbus_controller
    modbus_controller_id: d12_vfd
    name: "Frequency Source"
    address: 0x0003  # P0.03
    value_type: U_WORD
    skip_updates: 60  # Only poll every 2 minutes (config parameter, rarely changes)
    optionsmap:
      "Panel Potentiometer": 0
      "Digital Reference 1": 1
      "Digital Reference 2": 2
      "Analog AVI": 3
      "Combination": 4
      "Analog ACI": 5
      "Communication": 6
      "Pulse": 7

# ===== CONFIGURATION PARAMETERS =====
# You can add more parameter controls as needed:

# Example: Maximum Output Frequency (P0.04)
#  - platform: modbus_controller
#    modbus_controller_id: d12_vfd
#    name: "${friendly_name} Max Frequency"
#    address: 0x0004
#    value_type: U_WORD
#    unit_of_measurement: "Hz"
#    multiply: 0.1
